# Generated by Django 3.2.15 on 2023-07-08 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('lat', models.FloatField(db_index=True, verbose_name='широта')),
                ('lon', models.FloatField(db_index=True, verbose_name='долгота')),
                ('updated_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='обновлены')),
            ],
        ),
    ]
