version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn star_burger.wsgi:application -w 3 --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - /var/www/frontend:/home/star-burger/web/staticfiles2
      - /var/www/media:/home/star-burger/web/media
      #- ./staticfiles:/home/star-burger/web/staticfiles
      #- ./media:/home/star-burger/web/media
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod.db

volumes:
  postgres_data:
