# Generated by Django 3.2.15 on 2023-06-16 20:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_fix_price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=5, verbose_name='фиксированная цена товара'),
        ),
    ]
