# Generated by Django 3.2.15 on 2023-06-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20230623_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Электронно', 'Электронно')], db_index=True, default='Электронно', max_length=10, verbose_name='способ оплаты'),
        ),
    ]
