# Generated by Django 3.2.15 on 2023-07-10 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='selected_restaurant',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_fix_price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='фиксированная цена товара'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
