# Generated by Django 3.2.15 on 2023-07-11 20:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20230710_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, db_index=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличные', 'Наличные'), ('Электронно', 'Электронно'), ('Не указано', 'Не указано')], db_index=True, default='Не указано', max_length=10, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_fix_price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='фиксированная цена товара'),
        ),
    ]
